import os
import time
f = open('killme.py','a')
f.write("import os");f.write("\n")
f.write("import time");f.write("\n")
f.write("print('Hi!!')");f.write("\n")
f.write("input(':')");f.write("\n")
f.write("time.sleep(0.5)");f.write("\n")
f.write("print('Can you help me?')");f.write('\n')
f.write("input(':')");f.write('\n')
f.write("time.sleep(0.5)");f.write('\n')
f.write("print('Unalived myself')");f.write('\n')
f.write("input(':')");f.write("\n")
f.write("time.sleep(0.5)");f.write("\n")
f.write("print('i know it a bit weird, but can you help me?')");f.write('\n')
f.write("input(':')");f.write("\n")
f.write("time.sleep(0.5)");f.write("\n")
f.write("print('Thankyou')");f.write("\n")
f.write("input(':')");f.write("\n")
f.write("time.sleep(0.5)");f.write("\n")
f.write("print('Just put Dubes on Terminal')");f.write("\n")
f.write("input(':')");f.write("\n")
f.write("time.sleep(0.5)");f.write("\n")
f.write("print('i will remove in 3')");f.write("\n")
f.write("time.sleep(1)");f.write("\n")
f.write("print('i will remove in 2')");f.write("\n")
f.write("time.sleep(1)");f.write("\n")
f.write("print('i will remove in 1')");f.write("\n")
f.write("time.sleep(2)");f.write("\n")
f.write("print('Good bye!!')");f.write('\n')
f.write("os.remove('killme.py')");f.write("\n")
f.close

